"""The shipped panel layout, read as a layout rather than as a string.

Portlin ships this file in full, so a mistake in it is not a panel that looks
slightly wrong: it is a plugin that runs nothing, a readout with no command
behind it, or -- in the case configver guards -- an entire layout that is
discarded within a second of the first login with no error anywhere.

None of that is reachable by asserting substrings, which is what the panel was
checked with while it was two properties. These parse the XML and ask it
questions: do the declared ids and the defined plugins agree, is every plugin
type one the image installs, does the icon the menu button asks for exist.

The parser here is deliberately small and hand-written. xml.etree needs expat,
a C library that is not present on every developer's machine, and `make test`
running anywhere is a property this project sells.
"""

from __future__ import annotations

import re

import pytest

from portlin import package, packages
from portlin.__init__ import __version__

# <property name="x" type="t" value="v"/> and its container form. The layout is
# generated by portlin and its shape is known, so a full XML parser would buy
# nothing that this does not.
PROPERTY = re.compile(
    r'<property\s+name="(?P<name>[^"]+)"\s+type="(?P<type>[^"]+)"'
    r'(?:\s+value="(?P<value>[^"]*)")?'
)
VALUE = re.compile(r'<value\s+type="int"\s+value="(\d+)"')


@pytest.fixture(scope="module")
def layout() -> str:
    return package.text_files("portlin-desktop")[package.PANEL_DEFAULTS_FILE]


@pytest.fixture(scope="module")
def properties(layout: str) -> list[dict]:
    return [match.groupdict() for match in PROPERTY.finditer(layout)]


def _plugin_types(properties: list[dict]) -> dict[int, str]:
    """Every plugin-N declared, as {id: type}."""
    found = {}
    for entry in properties:
        match = re.fullmatch(r"plugin-(\d+)", entry["name"])
        if match and entry["type"] == "string":
            found[int(match.group(1))] = entry["value"]
    return found


def _declared_ids(layout: str) -> list[int]:
    """The ids in panel-1's plugin-ids array, in the order they appear."""
    block = layout[layout.index('name="plugin-ids"'):]
    return [int(value) for value in VALUE.findall(block[:block.index("</property>")])]


class TestTheLayoutIsAppliedAtAll:
    def test_it_declares_configver(self, properties):
        # The silent one. xfce4-panel/migrate reads configver, and below the
        # current version it loads Debian's default.xml and writes that into the
        # user's own file -- which beats every system default including this
        # one. Omitting it does not half-apply the layout; it makes the whole
        # file do nothing, within a second of the first login, with nothing
        # anywhere reporting it.
        names = {entry["name"] for entry in properties}
        assert "configver" in names

    def test_it_declares_a_panel_rather_than_only_plugin_properties(self, properties):
        # Layering properties onto Debian's numbering is what portlin did
        # before, and it could not add a plugin. A layout with no panels
        # property is that file again.
        names = {entry["name"] for entry in properties}
        assert "panels" in names and "panel-1" in names


class TestIdsAndDefinitionsAgree:
    def test_every_declared_id_has_a_definition(self, layout, properties):
        # An id in the array with no plugin-N behind it is an empty slot the
        # panel cannot fill, and xfce4-panel does not complain about it.
        defined = _plugin_types(properties)
        for identifier in _declared_ids(layout):
            assert identifier in defined, identifier

    def test_every_definition_is_actually_placed(self, layout, properties):
        # The other direction: a plugin defined but left out of the array is
        # configuration for something that never appears, which is how a
        # renumbering leaves a readout invisible and its settings intact.
        declared = set(_declared_ids(layout))
        for identifier in _plugin_types(properties):
            assert identifier in declared, identifier

    def test_no_id_is_placed_twice(self, layout):
        ids = _declared_ids(layout)
        assert len(ids) == len(set(ids))


class TestEveryPluginIsInstalled:
    # Plugin types that come from xfce4-panel itself rather than a separate
    # package. These ship with the panel and need no Depends of their own.
    STOCK = {"separator", "tasklist", "systray", "clock", "actions", "applicationsmenu"}

    # The rest, and the package that carries each. Named explicitly because
    # this is exactly what packages.py exists to keep visible: both arrive via
    # the xfce4-goodies metapackage today, and a metapackage's expansion is not
    # a promise across releases.
    FROM_A_PACKAGE = {
        "genmon": "xfce4-genmon-plugin",
        "whiskermenu": "xfce4-whiskermenu-plugin",
    }

    def test_the_image_installs_every_plugin_the_layout_names(self, properties):
        # A layout naming a plugin the image did not install is not a panel
        # missing an item. It is a hole, with nothing on screen to say why.
        installed = packages.resolve()
        for identifier, kind in _plugin_types(properties).items():
            if kind in self.STOCK:
                continue
            assert kind in self.FROM_A_PACKAGE, f"plugin-{identifier} is {kind}"
            assert self.FROM_A_PACKAGE[kind] in installed, kind

    def test_the_desktop_package_depends_on_them(self, properties):
        # Not derivable from the file list: these are named inside a data file
        # the package ships, so nothing but this holds them together.
        control = package.text_files("portlin-desktop")["DEBIAN/control"]
        depends = next(
            line for line in control.splitlines() if line.startswith("Depends:")
        )
        for kind in _plugin_types(properties).values():
            if kind in self.FROM_A_PACKAGE:
                assert self.FROM_A_PACKAGE[kind] in depends, kind


class TestTheMenuButton:
    def _menu(self, layout: str, properties: list[dict]) -> str:
        """The menu plugin's own block, found by type rather than by id.

        By type on purpose. Looking it up as plugin-1 is how the old override
        worked and why it depended on Debian's numbering; a test that repeats
        that assumption cannot notice the reordering it exists to survive.
        """
        identifier = next(
            number
            for number, kind in _plugin_types(properties).items()
            if kind in {"whiskermenu", "applicationsmenu"}
        )
        block = layout[layout.index(f'name="plugin-{identifier}"'):]
        return block[:block.index("</property>")]

    def test_it_is_labelled_with_the_running_version(self, layout, properties):
        assert (
            f'"button-title" type="string" value="Portlin {__version__}"'
            in self._menu(layout, properties)
        )

    def test_it_asks_for_an_icon_name_rather_than_a_path(self, layout, properties):
        # A name resolves under whatever icon theme is in force, including one
        # the user picks later in Settings. A path would freeze the mark to one
        # file and break the moment anything moved.
        menu = self._menu(layout, properties)
        assert f'"button-icon" type="string" value="{package.APP_ICON}"' in menu

    def test_the_icon_it_asks_for_is_one_the_package_ships(self, layout, properties):
        # Derived rather than retyped: the panel names an icon, and the package
        # has to install a file that name resolves to. hicolor is the icon
        # spec's terminal fallback, which is what makes it resolve under every
        # theme rather than only the one shipped today.
        assert package.HICOLOR_APP_ICON in package.binary_files("portlin-desktop")

    def test_both_the_icon_and_the_label_are_switched_on(self, layout, properties):
        menu = self._menu(layout, properties)
        assert '"show-button-title" type="bool" value="true"' in menu
        assert '"show-button-icon" type="bool" value="true"' in menu


class TestTheReadoutIsWiredUp:
    def test_the_genmon_id_matches_the_file_genmon_reads(self, properties):
        # genmon has no xfconf backend: it reads genmon-<id>.rc, looked up along
        # XDG_CONFIG_DIRS. A layout naming one id and a file named for another
        # is a panel item that runs nothing, and neither half looks wrong on
        # its own.
        types = _plugin_types(properties)
        assert types[package.STATS_PLUGIN_ID] == "genmon"

    def test_the_rc_file_ships_under_that_id(self):
        files = package.text_files("portlin-desktop")
        expected = (
            f"{package.XDG_OVERLAY}/xfce4/panel/genmon-{package.STATS_PLUGIN_ID}.rc"
        )
        assert expected in files

    def test_the_command_it_runs_is_one_the_package_installs(self):
        files = package.text_files("portlin-desktop")
        rc = files[
            f"{package.XDG_OVERLAY}/xfce4/panel/genmon-{package.STATS_PLUGIN_ID}.rc"
        ]
        command = next(
            line.removeprefix("Command=")
            for line in rc.splitlines()
            if line.startswith("Command=")
        )
        assert command.lstrip("/") in files

    def test_the_command_is_marked_executable(self):
        # A conffile pointing at a file dpkg installed 0644 is a readout that
        # never runs, and genmon reports that as an empty panel item.
        rc_command = "usr/bin/portlin-stats"
        assert rc_command in package.executable_paths("portlin-desktop")

    def test_it_is_an_absolute_path(self):
        # genmon parses Command through g_shell_parse_argv and runs it with
        # whatever PATH the panel inherited, which nobody controls.
        rc = package.text_files("portlin-desktop")[
            f"{package.XDG_OVERLAY}/xfce4/panel/genmon-{package.STATS_PLUGIN_ID}.rc"
        ]
        assert "Command=/" in rc


class TestSpacingIsOneRule:
    def test_every_separator_is_the_transparent_style(self, layout, properties):
        # Five separators, all style 0, is the whole spacing rule. A visible
        # line on one of them is the kind of thing that looks deliberate in a
        # diff and looks like a mistake on screen.
        for identifier, kind in _plugin_types(properties).items():
            if kind != "separator":
                continue
            block = layout[layout.index(f'name="plugin-{identifier}"'):]
            block = block[:block.index("</property>")]
            assert '"style" type="uint" value="0"' in block, identifier

    def test_exactly_one_separator_expands(self, layout):
        # The spring. Two would divide the free space and leave the readout
        # floating in the middle of the panel.
        assert layout.count('"expand" type="bool" value="true"') == 1
