"""Every configuration file portlin writes into the image, as pure functions.

These render text and nothing else. That matters more than it looks: fstab and
crypttab are where host-specific identifiers leak into an image and destroy its
portability, so they are worth asserting on character by character in tests
rather than discovering wrong on a stranger's laptop.
"""

from __future__ import annotations

from .layout import MAPPER_NAME

# noatime avoids a write on every read. commit=120 batches ext4 journal commits
# into two-minute windows instead of five-second ones, which meaningfully reduces
# write amplification on flash that has no wear levelling worth the name.
ROOT_MOUNT_OPTIONS = "defaults,noatime,commit=120,errors=remount-ro"
BOOT_MOUNT_OPTIONS = "defaults,noatime"
ESP_MOUNT_OPTIONS = "umask=0077,shortname=winnt"

# Where the unlock keyscript lands on the stick. Absolute, because crypttab
# names it that way and the initramfs hook copies whatever path it finds there.
STASH_KEYSCRIPT = "/lib/cryptsetup/scripts/portlin-stash-passphrase"

# Where the boot theme lands on the stick. Under /boot rather than the usual
# /usr/share/grub because /boot is the one filesystem GRUB can always read: on
# an encrypted stick everything else is still inside the LUKS container at the
# moment the menu is drawn.
GRUB_THEME_DIR = "/boot/grub/themes/portlin"
GRUB_THEME = f"{GRUB_THEME_DIR}/theme.txt"
# The ground the boot screen is drawn on. Beside the theme rather than under
# /usr/share/images for the same reason as the theme itself, and with one extra
# consequence: Debian's 05_debian_theme copies the background into /boot/grub
# whenever it lives on a different filesystem, so a path already on /boot is
# read in place and the stale copy is deleted instead of accumulating.
GRUB_BACKGROUND = f"{GRUB_THEME_DIR}/background.png"


def render_fstab(*, root_uuid: str, boot_uuid: str, esp_uuid: str) -> str:
    """Render /etc/fstab.

    UUIDs only. A device path such as /dev/sda4 is correct on exactly one
    machine and wrong on the next one, which is the whole failure mode portlin
    exists to avoid.
    """
    return "\n".join(
        [
            "# Generated by portlin. Identified by UUID so the stick boots on any",
            "# machine regardless of how its disks are enumerated.",
            f"UUID={root_uuid}\t/\text4\t{ROOT_MOUNT_OPTIONS}\t0 1",
            f"UUID={boot_uuid}\t/boot\text4\t{BOOT_MOUNT_OPTIONS}\t0 2",
            f"UUID={esp_uuid}\t/boot/efi\tvfat\t{ESP_MOUNT_OPTIONS}\t0 1",
            "tmpfs\t/tmp\ttmpfs\tdefaults,nosuid,nodev\t0 0",
            "",
        ]
    )


def render_crypttab(
    *, luks_uuid: str, discard: bool = False, stash_passphrase: bool = False
) -> str:
    """Render /etc/crypttab for the encrypted root.

    The initramfs cryptsetup hook reads this file to know what to unlock before
    handing off to the real root, so it must exist before update-initramfs runs.

    ``discard`` passes TRIM through to the underlying flash, which helps the
    stick's lifespan but reveals which blocks are unused to anyone inspecting the
    ciphertext. Off by default, matching the Debian installer.

    ``stash_passphrase`` routes the unlock through portlin's keyscript, which
    leaves the passphrase in a tmpfs file for the first-boot wizard to expand the
    mapping with. The wizard drops this option once it is done, so the stash is
    offered exactly once in a stick's life rather than on every boot.
    """
    options = ["luks"]
    if discard:
        options.append("discard")
    if stash_passphrase:
        options.append(f"keyscript={STASH_KEYSCRIPT}")
    return "\n".join(
        [
            "# Generated by portlin.",
            f"{MAPPER_NAME}\tUUID={luks_uuid}\tnone\t{','.join(options)}",
            "",
        ]
    )


def render_default_grub(*, offer_encryption: bool = False) -> str:
    """Render /etc/default/grub.

    GRUB_DISABLE_OS_PROBER is the single most important line in this file. With
    os-prober enabled, GRUB scans and mounts every disk it can see at
    grub-mkconfig time and, worse, the generated menu describes the build host's
    operating systems. On a stick meant to be plugged into other people's
    machines that is both wrong and invasive.

    ``offer_encryption`` puts portlin.encrypt=ask on the kernel command line,
    which is what triggers the initramfs to offer encryption on first boot. It
    lives on the command line rather than in a file because the initramfs would
    otherwise have to mount a filesystem just to discover whether to ask.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "GRUB_DEFAULT=0",
            "GRUB_TIMEOUT=3",
            "GRUB_TIMEOUT_STYLE=menu",
            'GRUB_DISTRIBUTOR="Portlin"',
            f'GRUB_CMDLINE_LINUX_DEFAULT="quiet{" portlin.encrypt=ask" if offer_encryption else ""}"',
            'GRUB_CMDLINE_LINUX=""',
            "GRUB_DISABLE_OS_PROBER=true",
            "GRUB_DISABLE_RECOVERY=false",
            "# /boot is plaintext, so GRUB itself never needs to unlock anything.",
            "GRUB_ENABLE_CRYPTODISK=n",
            'GRUB_PRELOAD_MODULES="part_gpt part_msdos"',
            # gfxmenu cannot draw in text mode, and a theme it cannot draw is a
            # theme GRUB silently falls back out of.
            "GRUB_GFXMODE=auto",
            f'GRUB_THEME="{GRUB_THEME}"',
            # A theme paints the menu; it does not paint the screen GRUB
            # switches to when it leaves the menu to report what it is booting.
            # That screen is the terminal's, and its background is whatever
            # 05_debian_theme resolved. Unset, that script walks its precedence
            # chain past this file, past /boot/grub, and lands on desktop-base,
            # putting Debian's wallpaper behind portlin's boot log. Naming a
            # file here short-circuits the chain at its first branch.
            f'GRUB_BACKGROUND="{GRUB_BACKGROUND}"',
            "",
        ]
    )


def render_initramfs_conf() -> str:
    """Render /etc/initramfs-tools/conf.d/portlin.

    MODULES=most builds an initramfs containing every storage and USB driver
    rather than only the ones the build host happens to need. It costs a few tens
    of megabytes and buys the ability to boot on unknown hardware, which is the
    entire point of this tool.

    RESUME=none stops the initramfs hunting for a hibernation image. Without it,
    booting on a machine with a swap partition can stall for a timeout while
    resume probing gives up.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "MODULES=most",
            "COMPRESS=zstd",
            "RESUME=none",
            "",
        ]
    )


def render_cryptsetup_hook_conf() -> str:
    """Render /etc/cryptsetup-initramfs/conf-hook.

    KEYMAP=y ships the console keymap into the initramfs. Without it the
    passphrase prompt is always US layout, so a passphrase containing symbols
    typed on a non-US keyboard is unenterable.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "CRYPTSETUP=y",
            "KEYMAP=y",
            "",
        ]
    )


def render_sources_list(*, suite: str, mirror: str, security_mirror: str, components: str) -> str:
    """Render /etc/apt/sources.list.

    The rolling suites have no -updates or -security pockets, so emitting them
    unconditionally would break every apt run on a sid build.
    """
    lines = [
        "# Generated by portlin.",
        f"deb {mirror} {suite} {components}",
    ]
    if suite not in ("sid", "unstable", "experimental"):
        lines.append(f"deb {mirror} {suite}-updates {components}")
        lines.append(f"deb {security_mirror} {suite}-security {components}")
    lines.append("")
    return "\n".join(lines)


def render_zram_conf() -> str:
    """Render /etc/default/zramswap.

    Compressed RAM instead of a swap partition. Swapping to USB flash is both
    painfully slow and a fast route to wearing the stick out.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "ALGO=zstd",
            "PERCENT=50",
            "",
        ]
    )


def render_policy_rc_d() -> str:
    """Render /usr/sbin/policy-rc.d used inside the build chroot.

    Exit code 101 tells Debian maintainer scripts "do not start this service".
    Without it, installing a package in a chroot tries to start a daemon against
    the build host's init and either fails the install or, worse, succeeds.
    """
    return "#!/bin/sh\n# Installed by portlin for the duration of the build.\nexit 101\n"


def render_os_release_extra(version: str) -> str:
    """Render /etc/portlin-release, a breadcrumb identifying how the stick was made."""
    return "\n".join(
        [
            f"PORTLIN_VERSION={version}",
            "PORTLIN_URL=https://github.com/sleep/Portlin",
            "",
        ]
    )
