"""Every configuration file portlin writes into the image, as pure functions.

These render text and nothing else. That matters more than it looks: fstab and
crypttab are where host-specific identifiers leak into an image and destroy its
portability, so they are worth asserting on character by character in tests
rather than discovering wrong on a stranger's laptop.
"""

from __future__ import annotations

from .layout import MAPPER_NAME

# noatime avoids a write on every read. commit=120 batches ext4 journal commits
# into two-minute windows instead of five-second ones, which meaningfully reduces
# write amplification on flash that has no wear levelling worth the name.
ROOT_MOUNT_OPTIONS = "defaults,noatime,commit=120,errors=remount-ro"
BOOT_MOUNT_OPTIONS = "defaults,noatime"
ESP_MOUNT_OPTIONS = "umask=0077,shortname=winnt"

# Where the unlock keyscript lands on the stick. Absolute, because crypttab
# names it that way and the initramfs hook copies whatever path it finds there.
STASH_KEYSCRIPT = "/lib/cryptsetup/scripts/portlin-stash-passphrase"

# Where the boot theme lands on the stick. Under /boot rather than the usual
# /usr/share/grub because /boot is the one filesystem GRUB can always read: on
# an encrypted stick everything else is still inside the LUKS container at the
# moment the menu is drawn.
GRUB_THEME_DIR = "/boot/grub/themes/portlin"
GRUB_THEME = f"{GRUB_THEME_DIR}/theme.txt"
# The ground the boot screen is drawn on. Beside the theme rather than under
# /usr/share/images for the same reason as the theme itself, and with one extra
# consequence: Debian's 05_debian_theme copies the background into /boot/grub
# whenever it lives on a different filesystem, so a path already on /boot is
# read in place and the stale copy is deleted instead of accumulating.
GRUB_BACKGROUND = f"{GRUB_THEME_DIR}/background.png"


def render_fstab(*, root_uuid: str, boot_uuid: str, esp_uuid: str) -> str:
    """Render /etc/fstab.

    UUIDs only. A device path such as /dev/sda4 is correct on exactly one
    machine and wrong on the next one, which is the whole failure mode portlin
    exists to avoid.
    """
    return "\n".join(
        [
            "# Generated by portlin. Identified by UUID so the stick boots on any",
            "# machine regardless of how its disks are enumerated.",
            f"UUID={root_uuid}\t/\text4\t{ROOT_MOUNT_OPTIONS}\t0 1",
            f"UUID={boot_uuid}\t/boot\text4\t{BOOT_MOUNT_OPTIONS}\t0 2",
            f"UUID={esp_uuid}\t/boot/efi\tvfat\t{ESP_MOUNT_OPTIONS}\t0 1",
            "tmpfs\t/tmp\ttmpfs\tdefaults,nosuid,nodev\t0 0",
            "",
        ]
    )


def render_crypttab(
    *, luks_uuid: str, discard: bool = False, stash_passphrase: bool = False
) -> str:
    """Render /etc/crypttab for the encrypted root.

    The initramfs cryptsetup hook reads this file to know what to unlock before
    handing off to the real root, so it must exist before update-initramfs runs.

    ``discard`` passes TRIM through to the underlying flash, which helps the
    stick's lifespan but reveals which blocks are unused to anyone inspecting the
    ciphertext. Off by default, matching the Debian installer.

    ``stash_passphrase`` routes the unlock through portlin's keyscript, which
    leaves the passphrase in a tmpfs file for the first-boot wizard to expand the
    mapping with. The wizard drops this option once it is done, so the stash is
    offered exactly once in a stick's life rather than on every boot.
    """
    options = ["luks"]
    if discard:
        options.append("discard")
    if stash_passphrase:
        options.append(f"keyscript={STASH_KEYSCRIPT}")
    return "\n".join(
        [
            "# Generated by portlin.",
            f"{MAPPER_NAME}\tUUID={luks_uuid}\tnone\t{','.join(options)}",
            "",
        ]
    )


def render_default_grub(*, offer_encryption: bool = False) -> str:
    """Render /etc/default/grub.

    GRUB_DISABLE_OS_PROBER is the single most important line in this file. With
    os-prober enabled, GRUB scans and mounts every disk it can see at
    grub-mkconfig time and, worse, the generated menu describes the build host's
    operating systems. On a stick meant to be plugged into other people's
    machines that is both wrong and invasive.

    ``offer_encryption`` puts portlin.encrypt=ask on the kernel command line,
    which is what triggers the initramfs to offer encryption on first boot. It
    lives on the command line rather than in a file because the initramfs would
    otherwise have to mount a filesystem just to discover whether to ask.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "GRUB_DEFAULT=0",
            "GRUB_TIMEOUT=3",
            "GRUB_TIMEOUT_STYLE=menu",
            'GRUB_DISTRIBUTOR="Portlin"',
            f'GRUB_CMDLINE_LINUX_DEFAULT="quiet{" portlin.encrypt=ask" if offer_encryption else ""}"',
            'GRUB_CMDLINE_LINUX=""',
            "GRUB_DISABLE_OS_PROBER=true",
            "GRUB_DISABLE_RECOVERY=false",
            "# /boot is plaintext, so GRUB itself never needs to unlock anything.",
            "GRUB_ENABLE_CRYPTODISK=n",
            'GRUB_PRELOAD_MODULES="part_gpt part_msdos"',
            # gfxmenu cannot draw in text mode, and a theme it cannot draw is a
            # theme GRUB silently falls back out of.
            "GRUB_GFXMODE=auto",
            f'GRUB_THEME="{GRUB_THEME}"',
            # A theme paints the menu; it does not paint the screen GRUB
            # switches to when it leaves the menu to report what it is booting.
            # That screen is the terminal's, and its background is whatever
            # 05_debian_theme resolved. Unset, that script walks its precedence
            # chain past this file, past /boot/grub, and lands on desktop-base,
            # putting Debian's wallpaper behind portlin's boot log. Naming a
            # file here short-circuits the chain at its first branch.
            f'GRUB_BACKGROUND="{GRUB_BACKGROUND}"',
            "",
        ]
    )


def render_initramfs_conf() -> str:
    """Render /etc/initramfs-tools/conf.d/portlin.

    MODULES=most builds an initramfs containing every storage and USB driver
    rather than only the ones the build host happens to need. It costs a few tens
    of megabytes and buys the ability to boot on unknown hardware, which is the
    entire point of this tool.

    RESUME=none stops the initramfs hunting for a hibernation image. Without it,
    booting on a machine with a swap partition can stall for a timeout while
    resume probing gives up.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "MODULES=most",
            "COMPRESS=zstd",
            "RESUME=none",
            "",
        ]
    )


def render_cryptsetup_hook_conf() -> str:
    """Render /etc/cryptsetup-initramfs/conf-hook.

    KEYMAP=y ships the console keymap into the initramfs. Without it the
    passphrase prompt is always US layout, so a passphrase containing symbols
    typed on a non-US keyboard is unenterable.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "CRYPTSETUP=y",
            "KEYMAP=y",
            "",
        ]
    )


def render_sources_list(*, suite: str, mirror: str, security_mirror: str, components: str) -> str:
    """Render /etc/apt/sources.list.

    The rolling suites have no -updates or -security pockets, so emitting them
    unconditionally would break every apt run on a sid build.
    """
    lines = [
        "# Generated by portlin.",
        f"deb {mirror} {suite} {components}",
    ]
    if suite not in ("sid", "unstable", "experimental"):
        lines.append(f"deb {mirror} {suite}-updates {components}")
        lines.append(f"deb {security_mirror} {suite}-security {components}")
    lines.append("")
    return "\n".join(lines)


def render_zram_conf() -> str:
    """Render /etc/default/zramswap.

    Compressed RAM instead of a swap partition. Swapping to USB flash is both
    painfully slow and a fast route to wearing the stick out.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "ALGO=zstd",
            "PERCENT=50",
            "",
        ]
    )


def render_policy_rc_d() -> str:
    """Render /usr/sbin/policy-rc.d used inside the build chroot.

    Exit code 101 tells Debian maintainer scripts "do not start this service".
    Without it, installing a package in a chroot tries to start a daemon against
    the build host's init and either fails the install or, worse, succeeds.
    """
    return "#!/bin/sh\n# Installed by portlin for the duration of the build.\nexit 101\n"


def render_os_release_extra(version: str) -> str:
    """Render /etc/portlin-release, a breadcrumb identifying how the stick was made."""
    return "\n".join(
        [
            f"PORTLIN_VERSION={version}",
            "PORTLIN_URL=https://github.com/sleep/Portlin",
            "",
        ]
    )


def render_bashrc(*, root: bool = False) -> str:
    """Render the themed interactive ~/.bashrc for root and for /etc/skel.

    Colors are indexes into the shipped 16-color terminal palette
    (portlin/resources/runtime/theme/terminalrc): 36 cyan user, 37 muted,
    97 paper host, 34 blue paths, 31 the accent -- which marks root and
    nothing else. Plain SGR codes rather than truecolor, because the
    linux VT and every minimal terminal understand these.

    The prompt is the classic user@host:path shape. ``root`` changes only
    the glyph color: \\$ renders # for root, and it alone is drawn in the
    accent -- the same reserved meaning the mark gives the encrypted root
    bar.
    """
    glyph = r"\[\e[31;1m\]" if root else r"\[\e[97;1m\]"
    ps1 = (
        r"\[\e]0;\u@\h: \w\a\]"  # window/tab title, as Debian's own skel ships.
        r"\[\e[36;1m\]\u\[\e[0;37m\]@\[\e[97;1m\]\h"
        r"\[\e[0;34m\]:\w"
        + glyph + r"\$ \[\e[0m\]"
    )
    lines = [
        "# ~/.bashrc -- the portlin interactive shell theme.",
        "#",
        "# Ships in portlin-desktop: this content lands at /etc/skel/.bashrc (for",
        "# every account the first-boot wizard creates) and at /root/.bashrc.",
        "# It is a conffile, so local edits survive upgrades.",
        "",
        "# If not running interactively, don't do anything.",
        "case $- in",
        "    *i*) ;;",
        "      *) return;;",
        "esac",
        "",
        "# History: Debian's stock behaviour.",
        "HISTCONTROL=ignoreboth",
        "HISTSIZE=1000",
        "HISTFILESIZE=2000",
        "shopt -s histappend",
        "shopt -s checkwinsize",
        "",
        "# Make less more friendly for non-text input files, see lesspipe(1).",
        "[ -x /usr/bin/lesspipe ] && eval \"$(SHELL=/bin/sh lesspipe)\"",
        "",
        "# Color ls output from the shipped terminal palette: directories blue,",
        "# links cyan, executables green.",
        "if [ -x /usr/bin/dircolors ]; then",
        "    test -r ~/.dircolors && eval \"$(dircolors -b ~/.dircolors)\" || eval \"$(dircolors -b)\"",
        "fi",
        "alias ll='ls -alF'",
        "alias la='ls -A'",
        "alias l='ls -CF'",
        "# neofetch is the name everyone types; fastfetch, installed by the",
        "# tools group, is the program that answers.",
        "alias neofetch='fastfetch'",
        "",
        "# Enable programmable completion features.",
        "if ! shopt -oq posix; then",
        "  if [ -f /usr/share/bash-completion/bash_completion ]; then",
        "    . /usr/share/bash-completion/bash_completion",
        "  elif [ -f /etc/bash_completion ]; then",
        "    . /etc/bash_completion",
        "  fi",
        "fi",
        "",
        "# The prompt: the classic user@host:path shape in the brand palette.",
        "# For root alone the glyph is the accent, where \\$ also renders #.",
        "# PS2 continues with the enclosure bar.",
        f"PS1='{ps1}'",
        "PS2='\\[\\e[37m\\]│ \\[\\e[0m\\]'",
        "",
        "# The welcome banner, once per terminal: SHLVL 1 means this shell owns",
        "# the window, so nested bash calls stay quiet. portlin-welcome ships in",
        "# this package; the guard keeps a hand-removed welcome silent.",
        "if [ \"${SHLVL:-1}\" = \"1\" ] && [ -t 1 ] && [ -x /usr/bin/portlin-welcome ]; then",
        "    /usr/bin/portlin-welcome 2>/dev/null || :",
        "fi",
        "",
    ]
    return "\n".join(lines)


def render_root_profile() -> str:
    """Render /root/.profile.

    Login shells (``su -``, ``ssh root@…``) read this and never ~/.bashrc, so
    an interactive root bash is pointed at the themed rc the same package
    ships. Nothing here sets PATH or environment: root's login environment is
    Debian's defaults, the theme only styles interactive use.
    """
    return "\n".join(
        [
            "# ~/.profile for root, shipped by portlin-desktop.",
            "",
            "# Interactive bash: pick up the themed ~/.bashrc this package also",
            "# ships, which login shells would otherwise never read.",
            "if [ -n \"$BASH\" ] && [ -f ~/.bashrc ]; then",
            "    . ~/.bashrc",
            "fi",
            "",
        ]
    )
