"""Every configuration file portlin writes into the image, as pure functions.

These render text and nothing else. That matters more than it looks: fstab and
crypttab are where host-specific identifiers leak into an image and destroy its
portability, so they are worth asserting on character by character in tests
rather than discovering wrong on a stranger's laptop.
"""

from __future__ import annotations

from . import buildinfo
from .layout import MAPPER_NAME

# noatime avoids a write on every read. commit=120 batches ext4 journal commits
# into two-minute windows instead of five-second ones, which meaningfully reduces
# write amplification on flash that has no wear levelling worth the name.
ROOT_MOUNT_OPTIONS = "defaults,noatime,commit=120,errors=remount-ro"
BOOT_MOUNT_OPTIONS = "defaults,noatime"
ESP_MOUNT_OPTIONS = "umask=0077,shortname=winnt"

# Where the unlock keyscript lands on the stick. Absolute, because crypttab
# names it that way and the initramfs hook copies whatever path it finds there.
STASH_KEYSCRIPT = "/lib/cryptsetup/scripts/portlin-stash-passphrase"

# Where the boot theme lands on the stick. Under /boot rather than the usual
# /usr/share/grub because /boot is the one filesystem GRUB can always read: on
# an encrypted stick everything else is still inside the LUKS container at the
# moment the menu is drawn.
GRUB_THEME_DIR = "/boot/grub/themes/portlin"
GRUB_THEME = f"{GRUB_THEME_DIR}/theme.txt"
# The ground the boot screen is drawn on. Beside the theme rather than under
# /usr/share/images for the same reason as the theme itself, and with one extra
# consequence: Debian's 05_debian_theme copies the background into /boot/grub
# whenever it lives on a different filesystem, so a path already on /boot is
# read in place and the stale copy is deleted instead of accumulating.
GRUB_BACKGROUND = f"{GRUB_THEME_DIR}/background.png"


def render_fstab(*, root_uuid: str, boot_uuid: str, esp_uuid: str) -> str:
    """Render /etc/fstab.

    UUIDs only. A device path such as /dev/sda4 is correct on exactly one
    machine and wrong on the next one, which is the whole failure mode portlin
    exists to avoid.
    """
    return "\n".join(
        [
            "# Generated by portlin. Identified by UUID so the stick boots on any",
            "# machine regardless of how its disks are enumerated.",
            f"UUID={root_uuid}\t/\text4\t{ROOT_MOUNT_OPTIONS}\t0 1",
            f"UUID={boot_uuid}\t/boot\text4\t{BOOT_MOUNT_OPTIONS}\t0 2",
            f"UUID={esp_uuid}\t/boot/efi\tvfat\t{ESP_MOUNT_OPTIONS}\t0 1",
            "tmpfs\t/tmp\ttmpfs\tdefaults,nosuid,nodev\t0 0",
            "",
        ]
    )


def render_crypttab(
    *, luks_uuid: str, discard: bool = False, stash_passphrase: bool = False
) -> str:
    """Render /etc/crypttab for the encrypted root.

    The initramfs cryptsetup hook reads this file to know what to unlock before
    handing off to the real root, so it must exist before update-initramfs runs.

    ``discard`` passes TRIM through to the underlying flash, which helps the
    stick's lifespan but reveals which blocks are unused to anyone inspecting the
    ciphertext. Off by default, matching the Debian installer.

    ``stash_passphrase`` routes the unlock through portlin's keyscript, which
    leaves the passphrase in a tmpfs file for the first-boot wizard to expand the
    mapping with. The wizard drops this option once it is done, so the stash is
    offered exactly once in a stick's life rather than on every boot.
    """
    options = ["luks"]
    if discard:
        options.append("discard")
    if stash_passphrase:
        options.append(f"keyscript={STASH_KEYSCRIPT}")
    return "\n".join(
        [
            "# Generated by portlin.",
            f"{MAPPER_NAME}\tUUID={luks_uuid}\tnone\t{','.join(options)}",
            "",
        ]
    )


def render_default_grub(*, offer_encryption: bool = False) -> str:
    """Render /etc/default/grub.

    GRUB_DISABLE_OS_PROBER is the single most important line in this file. With
    os-prober enabled, GRUB scans and mounts every disk it can see at
    grub-mkconfig time and, worse, the generated menu describes the build host's
    operating systems. On a stick meant to be plugged into other people's
    machines that is both wrong and invasive.

    ``offer_encryption`` puts portlin.encrypt=ask on the kernel command line,
    which is what triggers the initramfs to offer encryption on first boot. It
    lives on the command line rather than in a file because the initramfs would
    otherwise have to mount a filesystem just to discover whether to ask.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "GRUB_DEFAULT=0",
            "GRUB_TIMEOUT=3",
            "GRUB_TIMEOUT_STYLE=menu",
            'GRUB_DISTRIBUTOR="Portlin"',
            f'GRUB_CMDLINE_LINUX_DEFAULT="quiet{" portlin.encrypt=ask" if offer_encryption else ""}"',
            'GRUB_CMDLINE_LINUX=""',
            "GRUB_DISABLE_OS_PROBER=true",
            "GRUB_DISABLE_RECOVERY=false",
            "# /boot is plaintext, so GRUB itself never needs to unlock anything.",
            "GRUB_ENABLE_CRYPTODISK=n",
            'GRUB_PRELOAD_MODULES="part_gpt part_msdos"',
            # gfxmenu cannot draw in text mode, and a theme it cannot draw is a
            # theme GRUB silently falls back out of.
            "GRUB_GFXMODE=auto",
            f'GRUB_THEME="{GRUB_THEME}"',
            # A theme paints the menu; it does not paint the screen GRUB
            # switches to when it leaves the menu to report what it is booting.
            # That screen is the terminal's, and its background is whatever
            # 05_debian_theme resolved. Unset, that script walks its precedence
            # chain past this file, past /boot/grub, and lands on desktop-base,
            # putting Debian's wallpaper behind portlin's boot log. Naming a
            # file here short-circuits the chain at its first branch.
            f'GRUB_BACKGROUND="{GRUB_BACKGROUND}"',
            "",
        ]
    )


def render_initramfs_conf() -> str:
    """Render /etc/initramfs-tools/conf.d/portlin.

    MODULES=most builds an initramfs containing every storage and USB driver
    rather than only the ones the build host happens to need. It costs a few tens
    of megabytes and buys the ability to boot on unknown hardware, which is the
    entire point of this tool.

    RESUME=none stops the initramfs hunting for a hibernation image. Without it,
    booting on a machine with a swap partition can stall for a timeout while
    resume probing gives up.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "MODULES=most",
            "COMPRESS=zstd",
            "RESUME=none",
            "",
        ]
    )


def render_cryptsetup_hook_conf() -> str:
    """Render /etc/cryptsetup-initramfs/conf-hook.

    KEYMAP=y ships the console keymap into the initramfs. Without it the
    passphrase prompt is always US layout, so a passphrase containing symbols
    typed on a non-US keyboard is unenterable.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "CRYPTSETUP=y",
            "KEYMAP=y",
            "",
        ]
    )


# Where remote unlock is switched on and off, and the port its SSH server
# listens on. One file, read by three things: the initramfs gate hook decides
# from it whether dropbear goes into the initramfs at all, the premount script
# reads the port out of the copy the hook put in the initramfs, and the
# first-boot wizard and portlin-remote-unlock write it.
REMOTE_UNLOCK_CONF = "/etc/portlin/remote-unlock.conf"

# Not 22. The initramfs server has its own host key, and a client that had
# already talked to the stick's real sshd on the same address would otherwise
# refuse with "REMOTE HOST IDENTIFICATION HAS CHANGED". A port of its own
# gives it a known_hosts entry of its own.
REMOTE_UNLOCK_PORT = 2222


def render_remote_unlock_conf(*, enabled: bool = False, port: int = REMOTE_UNLOCK_PORT) -> str:
    """Render /etc/portlin/remote-unlock.conf.

    Off by default, whatever dropbear-initramfs's own hook would do: that
    hook puts dropbear in every initramfs it is installed on, and a stick
    that answers SSH before it has unlocked, on whatever network it was
    plugged into, is not something anyone should get without asking.
    """
    return "\n".join(
        [
            "# Written by portlin. Whether the initramfs answers SSH before the root",
            "# filesystem is unlocked, and on which port. Change it with",
            "# portlin-remote-unlock, which also rebuilds the initramfs.",
            f"enabled={int(enabled)}",
            f"port={port}",
            "",
        ]
    )


def render_sources_list(*, suite: str, mirror: str, security_mirror: str, components: str) -> str:
    """Render /etc/apt/sources.list.

    The rolling suites have no -updates or -security pockets, so emitting them
    unconditionally would break every apt run on a sid build.
    """
    lines = [
        "# Generated by portlin.",
        f"deb {mirror} {suite} {components}",
    ]
    if suite not in ("sid", "unstable", "experimental"):
        lines.append(f"deb {mirror} {suite}-updates {components}")
        lines.append(f"deb {security_mirror} {suite}-security {components}")
    lines.append("")
    return "\n".join(lines)


def render_zram_conf() -> str:
    """Render /etc/default/zramswap.

    Compressed RAM instead of a swap partition. Swapping to USB flash is both
    painfully slow and a fast route to wearing the stick out.
    """
    return "\n".join(
        [
            "# Generated by portlin.",
            "ALGO=zstd",
            "PERCENT=50",
            "",
        ]
    )


def render_policy_rc_d() -> str:
    """Render /usr/sbin/policy-rc.d used inside the build chroot.

    Exit code 101 tells Debian maintainer scripts "do not start this service".
    Without it, installing a package in a chroot tries to start a daemon against
    the build host's init and either fails the install or, worse, succeeds.
    """
    return "#!/bin/sh\n# Installed by portlin for the duration of the build.\nexit 101\n"


def render_os_release_extra(version: str, commit: str = "") -> str:
    """Render /etc/portlin-release, a breadcrumb identifying how the stick was made.

    PORTLIN_COMMIT is left out rather than written empty when the source is
    unknown, so every reader's "unknown" default is the one that shows.
    """
    lines = [f"PORTLIN_VERSION={version}"]
    if commit:
        lines.append(f"PORTLIN_COMMIT={commit}")
    lines += ["PORTLIN_URL=https://github.com/sleep/Portlin", ""]
    return "\n".join(lines)


# Stands in theme.txt for the build line, filled in at write time for the same
# reason /etc/portlin-release is: the tarball can be months older than the stick.
BOOT_THEME_BUILD_PLACEHOLDER = "@PORTLIN_BUILD@"


def render_boot_theme(theme: str, version: str, commit: str = "") -> str:
    """Fill the build line into the GRUB theme.

    Quotes are dropped from the label text because a GRUB theme string has no
    escape for them, and one stray quote would end the label early and leave
    the rest of the file unparsed.
    """
    build = f"portlin {buildinfo.describe(version, commit)}".replace('"', "")
    return theme.replace(BOOT_THEME_BUILD_PLACEHOLDER, build)


def render_bashrc(*, root: bool = False) -> str:
    """Render the themed interactive ~/.bashrc for root and for /etc/skel.

    Colors are indexes into the shipped 16-color terminal palette
    (portlin/resources/runtime/theme/terminalrc): 36 cyan user, 37 muted,
    97 paper host, 34 blue paths, 31 the accent -- which marks root and
    nothing else. Plain SGR codes rather than truecolor, because the
    linux VT and every minimal terminal understand these.

    The prompt is the classic user@host:path shape. ``root`` changes only
    the glyph color: \\$ renders # for root, and it alone is drawn in the
    accent -- the same reserved meaning the mark gives the encrypted root
    bar.
    """
    glyph = r"\[\e[31;1m\]" if root else r"\[\e[97;1m\]"
    ps1 = (
        r"\[\e]0;\u@\h: \w\a\]"  # window/tab title, as Debian's own skel ships.
        r"\[\e[36;1m\]\u\[\e[0;37m\]@\[\e[97;1m\]\h"
        r"\[\e[0;34m\]:\w"
        + glyph + r"\$ \[\e[0m\]"
    )
    lines = [
        "# ~/.bashrc -- the portlin interactive shell theme.",
        "#",
        "# Ships in portlin-desktop: this content lands at /etc/skel/.bashrc (for",
        "# every account the first-boot wizard creates) and at /root/.bashrc.",
        "# It is a conffile, so local edits survive upgrades.",
        "",
        "# If not running interactively, don't do anything.",
        "case $- in",
        "    *i*) ;;",
        "      *) return;;",
        "esac",
        "",
        "# History: Debian's stock behaviour.",
        "HISTCONTROL=ignoreboth",
        "HISTSIZE=1000",
        "HISTFILESIZE=2000",
        "shopt -s histappend",
        "shopt -s checkwinsize",
        "",
        "# Make less more friendly for non-text input files, see lesspipe(1).",
        "[ -x /usr/bin/lesspipe ] && eval \"$(SHELL=/bin/sh lesspipe)\"",
        "",
        "# Color ls output from the shipped terminal palette: directories blue,",
        "# links cyan, executables green.",
        "if [ -x /usr/bin/dircolors ]; then",
        "    test -r ~/.dircolors && eval \"$(dircolors -b ~/.dircolors)\" || eval \"$(dircolors -b)\"",
        "fi",
        "alias ll='ls -alF'",
        "alias la='ls -A'",
        "alias l='ls -CF'",
        "# neofetch is the name everyone types; fastfetch, installed by the",
        "# tools group, is the program that answers.",
        "alias neofetch='fastfetch'",
        "",
        "# Enable programmable completion features.",
        "if ! shopt -oq posix; then",
        "  if [ -f /usr/share/bash-completion/bash_completion ]; then",
        "    . /usr/share/bash-completion/bash_completion",
        "  elif [ -f /etc/bash_completion ]; then",
        "    . /etc/bash_completion",
        "  fi",
        "fi",
        "",
        "# The prompt: the classic user@host:path shape in the brand palette.",
        "# For root alone the glyph is the accent, where \\$ also renders #.",
        "# PS2 continues with the enclosure bar.",
        f"PS1='{ps1}'",
        "PS2='\\[\\e[37m\\]│ \\[\\e[0m\\]'",
        "",
        "# The welcome banner, once per terminal: SHLVL 1 means this shell owns",
        "# the window, so nested bash calls stay quiet. portlin-welcome ships in",
        "# this package; the guard keeps a hand-removed welcome silent.",
        "if [ \"${SHLVL:-1}\" = \"1\" ] && [ -t 1 ] && [ -x /usr/bin/portlin-welcome ]; then",
        "    /usr/bin/portlin-welcome 2>/dev/null || :",
        "fi",
        "",
    ]
    return "\n".join(lines)


def render_zshrc() -> str:
    """Render the themed interactive ~/.zshrc, for /etc/skel and for root alike.

    The same prompt and palette as render_bashrc, so switching shells
    changes what the shell can do rather than what the terminal looks like.
    One file serves both: %(!.) is zsh's own root test, so the accent glyph
    needs no second render.

    On top of the bash theme: git state beside the path, the exit status
    and duration of the last command on the right, history shared between
    terminals, menu completion, and Debian's autosuggestion and syntax
    highlighting plugins when they are installed. None of it fetches
    anything or needs a framework.
    """
    prompt = (
        "%B%F{6}%n%f%b%F{7}@%f%B%F{15}%m%b%f"
        "%F{4}:%~%f"
        "${_portlin_git}"
        "%B%(!.%F{1}.%F{15})%(!.#.$)%f%b "
    )
    lines = [
        "# ~/.zshrc -- the portlin interactive shell theme, for zsh.",
        "#",
        "# Ships in portlin-desktop: this content lands at /etc/skel/.zshrc (for",
        "# every account the first-boot wizard creates) and at /root/.zshrc, and",
        "# portlin-shell copies it into a home that has none. The skel copy is a",
        "# conffile, so local edits survive upgrades.",
        "",
        "[[ -o interactive ]] || return",
        "",
        "# History is shared between open terminals as each command finishes, with",
        "# timestamps: `history -i` shows them.",
        "HISTFILE=~/.zsh_history",
        "HISTSIZE=10000",
        "SAVEHIST=10000",
        "setopt extended_history share_history hist_ignore_dups hist_ignore_space",
        "setopt hist_reduce_blanks hist_verify",
        "setopt auto_cd auto_pushd pushd_ignore_dups pushd_silent",
        "setopt interactive_comments no_beep prompt_subst transient_rprompt",
        "",
        "# Ctrl-W and Alt-B stop at a slash, as they do in bash.",
        "WORDCHARS=${WORDCHARS//\\/}",
        "",
        "# Make less more friendly for non-text input files, see lesspipe(1).",
        "[[ -x /usr/bin/lesspipe ]] && eval \"$(SHELL=/bin/sh lesspipe)\"",
        "",
        "# Color ls output from the shipped terminal palette: directories blue,",
        "# links cyan, executables green.",
        "if [[ -x /usr/bin/dircolors ]]; then",
        "    if [[ -r ~/.dircolors ]]; then",
        "        eval \"$(dircolors -b ~/.dircolors)\"",
        "    else",
        "        eval \"$(dircolors -b)\"",
        "    fi",
        "fi",
        "alias ls='ls --color=auto'",
        "alias grep='grep --color=auto'",
        "alias ll='ls -alF'",
        "alias la='ls -A'",
        "alias l='ls -CF'",
        "alias neofetch='fastfetch'",
        "",
        "# The everyday git aliases, spelled as oh-my-zsh's git plugin spells them,",
        "# so hands trained there work here.",
        "alias g='git'",
        "alias ga='git add'",
        "alias gaa='git add --all'",
        "alias gb='git branch'",
        "alias gc='git commit --verbose'",
        "alias gcmsg='git commit --message'",
        "alias gco='git checkout'",
        "alias gsw='git switch'",
        "alias gd='git diff'",
        "alias gds='git diff --staged'",
        "alias gl='git pull'",
        "alias gp='git push'",
        "alias gst='git status'",
        "alias gss='git status --short'",
        "alias glog='git log --oneline --decorate --graph'",
        "",
        "# Emacs keys, as in bash. Up and Down search history for what is already",
        "# typed; both escape forms are bound because terminals differ in which",
        "# they send.",
        "bindkey -e",
        "autoload -Uz up-line-or-beginning-search down-line-or-beginning-search edit-command-line",
        "zle -N up-line-or-beginning-search",
        "zle -N down-line-or-beginning-search",
        "zle -N edit-command-line",
        "bindkey '^[[A' up-line-or-beginning-search",
        "bindkey '^[OA' up-line-or-beginning-search",
        "bindkey '^[[B' down-line-or-beginning-search",
        "bindkey '^[OB' down-line-or-beginning-search",
        "bindkey '^[[H' beginning-of-line",
        "bindkey '^[OH' beginning-of-line",
        "bindkey '^[[F' end-of-line",
        "bindkey '^[OF' end-of-line",
        "bindkey '^[[3~' delete-char",
        "bindkey '^[[1;5C' forward-word",
        "bindkey '^[[1;5D' backward-word",
        "bindkey '^[[Z' reverse-menu-complete",
        "bindkey '^X^E' edit-command-line",
        "",
        "# Completion: an arrow-key menu, lowercase matching uppercase, ls's colors.",
        "zmodload zsh/complist",
        "autoload -Uz compinit",
        "mkdir -p ~/.cache/zsh",
        "compinit -d ~/.cache/zsh/zcompdump",
        "zstyle ':completion:*' menu select",
        "zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*'",
        "zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}",
        "zstyle ':completion:*' group-name ''",
        "zstyle ':completion:*:descriptions' format '%F{7}%d%f'",
        "zstyle ':completion:*' use-cache on",
        "zstyle ':completion:*' cache-path ~/.cache/zsh/compcache",
        "",
        "# Git state for the prompt, from one `git status` per prompt: the branch,",
        "# commits ahead and behind its upstream, then counts of staged, changed,",
        "# conflicted and untracked files. Set PORTLIN_PROMPT_GIT=0 to leave it out,",
        "# for a repository big enough that the status is slow. Every % is doubled",
        "# because the result is read as prompt escapes.",
        "_portlin_git_status() {",
        "    _portlin_git=",
        "    [[ ${PORTLIN_PROMPT_GIT:-1} == 0 ]] && return",
        "    (( $+commands[git] )) || return",
        "    local out line oid branch",
        "    local -i ahead=0 behind=0 staged=0 changed=0 conflicts=0 untracked=0",
        "    out=$(GIT_OPTIONAL_LOCKS=0 git status --porcelain=v2 --branch 2>/dev/null) || return",
        "    for line in ${(f)out}; do",
        "        case $line in",
        "            ('# branch.oid '*) oid=${line#'# branch.oid '} ;;",
        "            ('# branch.head '*) branch=${line#'# branch.head '} ;;",
        "            ('# branch.ab '*) ahead=${${line#*+}%% *}; behind=${line##*-} ;;",
        "            ([12]' '*)",
        "                [[ ${line[3]} != . ]] && (( ++staged ))",
        "                [[ ${line[4]} != . ]] && (( ++changed )) ;;",
        "            ('u '*) (( ++conflicts )) ;;",
        "            ('? '*) (( ++untracked )) ;;",
        "        esac",
        "    done",
        "    [[ -n $branch ]] || return",
        "    [[ $branch == '(detached)' ]] && branch=${oid[1,7]}",
        "    local part=\"%F{5}${branch//\\%/%%}%f\"",
        "    (( ahead )) && part+=\" %F{7}↑$ahead%f\"",
        "    (( behind )) && part+=\" %F{7}↓$behind%f\"",
        "    (( staged )) && part+=\" %F{2}+$staged%f\"",
        "    (( changed )) && part+=\" %F{3}*$changed%f\"",
        "    (( conflicts )) && part+=\" %B%F{3}!$conflicts%f%b\"",
        "    (( untracked )) && part+=\" %F{7}?$untracked%f\"",
        "    _portlin_git=\" %F{7}(%f$part%F{7})%f\"",
        "}",
        "",
        "# The right side, after a command ran: its exit status when it failed, by",
        "# signal name when a signal ended it, and how long it took when that was",
        "# five seconds or more. Never the accent, which marks root alone.",
        "zmodload zsh/datetime",
        "_portlin_preexec() {",
        "    _portlin_started=$EPOCHREALTIME",
        "    [[ $TERM == (linux|dumb) ]] || print -rn -- $'\\e]0;'\"${(V)1}\"$'\\a'",
        "}",
        "",
        "_portlin_precmd() {",
        "    local -i code=$?",
        "    local -a parts",
        "    if [[ -n $_portlin_started ]]; then",
        "        local -i took=$(( EPOCHREALTIME - _portlin_started ))",
        "        unset _portlin_started",
        "        if (( code > 128 && code - 127 <= ${#signals} )); then",
        "            parts+=(\"%F{3}${signals[code - 127]}%f\")",
        "        elif (( code )); then",
        "            parts+=(\"%F{3}exit $code%f\")",
        "        fi",
        "        if (( took >= 3600 )); then",
        "            parts+=(\"%F{7}$(( took / 3600 ))h $(( took % 3600 / 60 ))m%f\")",
        "        elif (( took >= 60 )); then",
        "            parts+=(\"%F{7}$(( took / 60 ))m $(( took % 60 ))s%f\")",
        "        elif (( took >= 5 )); then",
        "            parts+=(\"%F{7}${took}s%f\")",
        "        fi",
        "    fi",
        "    _portlin_status=${(j: :)parts}",
        "    _portlin_git_status",
        "    [[ $TERM == (linux|dumb) ]] || print -Pn '\\e]0;%n@%m: %~\\a'",
        "}",
        "",
        "autoload -Uz add-zsh-hook",
        "add-zsh-hook preexec _portlin_preexec",
        "add-zsh-hook precmd _portlin_precmd",
        "",
        "# The prompt: the classic user@host:path shape in the brand palette, the",
        "# bash theme's own, with git state after the path. For root alone the",
        "# glyph is the accent, and # rather than $. Background jobs are counted",
        "# on the right. PROMPT2 continues with the enclosure bar.",
        f"PROMPT='{prompt}'",
        "RPROMPT='${_portlin_status}%(1j. %F{7}jobs %j%f.)'",
        "PROMPT2='%F{7}│%f '",
        "",
        "if [[ -r /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then",
        "    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=7'",
        "    source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh",
        "fi",
        "",
        "# Last, because it wraps every line-editor widget defined before it. Its",
        "# stock styles draw unknown commands in red, which is the accent, and",
        "# comments in black, which is the background.",
        "if [[ -r /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then",
        "    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
        "    ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=3,bold'",
        "    ZSH_HIGHLIGHT_STYLES[comment]='fg=7'",
        "fi",
        "",
        "# The welcome banner, once per terminal: SHLVL 1 means this shell owns",
        "# the window, so nested shells stay quiet. portlin-welcome ships in",
        "# this package; the guard keeps a hand-removed welcome silent.",
        "if [[ ${SHLVL:-1} == 1 && -t 1 && -x /usr/bin/portlin-welcome ]]; then",
        "    /usr/bin/portlin-welcome 2>/dev/null || :",
        "fi",
        "",
    ]
    return "\n".join(lines)


def render_root_profile() -> str:
    """Render /root/.profile.

    Login shells (``su -``, ``ssh root@…``) read this and never ~/.bashrc, so
    an interactive root bash is pointed at the themed rc the same package
    ships. Nothing here sets PATH or environment: root's login environment is
    Debian's defaults, the theme only styles interactive use.
    """
    return "\n".join(
        [
            "# ~/.profile for root, shipped by portlin-desktop.",
            "",
            "# Interactive bash: pick up the themed ~/.bashrc this package also",
            "# ships, which login shells would otherwise never read.",
            "if [ -n \"$BASH\" ] && [ -f ~/.bashrc ]; then",
            "    . ~/.bashrc",
            "fi",
            "",
        ]
    )
